batch_size : 128
buffer_size : 50000
net_sync_period : 10
n_episodes : 10000
lr : 0.0006

epsilon_decay: {'period': 10000,
'start': 1,
'stop': .05,
'shape': 'exponential'}

gamma : .9
use_gpu: True
unique_net: False
use_mixer: True
use_writer: True
mixer_hidden_layer: 64
optimizer: 'Adam'
gamma: 0.9
max_depth: 0 # 0 = no limit

hidden_layers: [64,64] # Agents Q-Networks