agents_description : [
{'pos0': 'random','team': 'blue','replicas': 2},
{'pos0': 'random','team': 'red','policy': 'random','replicas': 2}
] 
size: [10,10]
visibility: 12
R50: 10
obstacles: []
borders_in_obstacles: False
N_aim: 5
max_cycles: 25
ammo: -1
observation_mode: 'array'