agents_description : [
{'pos0': 'random','team': 'blue','replicas': 2},
{'pos0': 'random','team': 'red','policy': 'random','replicas': 2}
] 
size: [10,10]
visibility: 7
R50: 5
obstacles: []
N_aim: 5
max_cycles: 25
ammo: 5
random_ids: True