  # Encoder:
input_size : 3
output_size : 10
pre_processing_layers : [8]
num_layers : 2
post_processing_layers : []
rnn_size: 10
rnn_type: 'LSTM'

  # Decoder:
decoder_hidden_layers : [16,16]

  # Env params:
size : [50,50]
N_obstacles : 10
borders_in_obstacles : False
visibility : 5

agents_description: [
{'pos0':'random','team':'blue','replicas':4},
{'pos0':'random','team':'red', 'replicas':4}]

  # Training params:
batch_size : 1000
elements_per_sample : 10
epochs : 1000
use_gpu : True
load_model : False
save_model : True