  # Encoder:
input_size : 3
output_size : 20
pre_processing_layers : [10]
num_layers : 1
post_processing_layers : []
rnn_size: 20
rnn_type: 'LSTM'

  # Decoder:
decoder_hidden_layers : [20]

  # Env params:
visibility : 20
max_foes : 4
max_id : 10

  # Training params:
batch_size : 128
epochs : 100000
use_gpu : True
use_writer : True
load_model : False
save_model : True
start_freezing : 1000000
freeze_period : 100