########## LEARNING PARAMETERS ##########

batch_size : 128
buffer_size : 200000
n_episodes : 50000
lr : 0.001

epsilon_decay: {'period': 50000,
'start': 1,
'stop': .02,
'shape': 'exponential'}

gamma : .9
net_sync_period : 25
use_gpu: true

########## ENVIRONMENT PARAMETERS ##########
size : [10,10]
agents_description : [
{'pos0': 'random','team': 'blue'},
{'pos0': 'random','team': 'red','policy': 'random'}
] 
N_aim: 5 
visibility: 7
R50: 5
max_cycles: 25
render: false
random_ids: True
ammo: 5
random_obstacles: 10
observation_mode: 'array'


########## AGENT PARAMETERS ##########
pre_processing_layers: []
post_processing_layers: []
rnn_size: 64
num_layers: 1
rnn_type: 'GRU'
max_depth: 0